#!/usr/bin/python

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../../../../utils"))
import utils

"""
GROUPS

Defines constants for CONF (the name of the conference), and for the names of each group.
All other groups will be named by joining the name with CONF: <CONF>/<NAME>

Example:

    CONF = 'my.conference/2017'
    PROGRAM_CHAIRS = 'Program_Chairs'

    --> my.conference/2017/Program_Chairs

"""

CONF = "ICML.cc/2017/WHI"
ADMIN = CONF + '/Admin'
PROGRAM_CHAIRS = CONF + '/Program_Chairs'
AREA_CHAIRS = CONF + '/Area_Chairs'
REVIEWERS = CONF + '/Reviewers'
# June 16, 2017 (11:59 pm AoE) = June 17, 7:59am EST
DUE_TIMESTAMP = 1497718800000
# June 28, 2017  (11:59 pm AoE) = June 29, 7:59am EST
REVIEW_DUE = 1498737599000
WEBPATH = utils.get_path('../webfield/conf.html', __file__)


"""
INVITATIONS

Defines constants for various invitations.
The full name of an invitation will be generated by joining the name with CONF by "/-/": <CONF>/-/<INVITATION_NAME>

Example:

    CONF = 'my.conference/2017'
    SUBMISSION = 'Submission'

    --> my.conference/2017/-/Submission

"""

SUBMISSION = CONF + '/-/Submission'
COMMENT = CONF + '/-/Comment'


"""
PARAMETERS

Dictionaries that represent argument combinations defining Group and Invitation permissions.

Example:

    restricted = {
        'readers': [CONF],
        'writers': [CONF],
        'signatories': [CONF],
    }

    The "restricted" configuration above will only allow the CONF group to read, write, and sign
    for the newly created Group that uses it.
"""

conf_params = {
    'readers': ['everyone'],
    'writers': [CONF],
    'signatories': [CONF],
    'web': WEBPATH
}

group_params = {
    'readers': [CONF],
    'writers': [CONF],
    'signatories': [CONF],
}

submission_params = {
    'readers': ['everyone'],
    'writers': [CONF],
    'invitees': ['~'],
    'signatures': [CONF],
    'process': utils.get_path('../process/submissionProcess.js', __file__)
}

comment_params = {
    'readers': ['everyone'],
    'writers': [CONF],
    'invitees': ['~'],
    'signatures': [CONF],
    'process': utils.get_path('../process/commentProcess.js', __file__)
}

review_content = {
    'title': {
        'order': 1,
        'value-regex': '.{0,500}',
        'description': 'Brief summary of your review.',
        'required': True
    },
    'review': {
        'order': 2,
        'value-regex': '[\\S\\s]{1,5000}',
        'description': 'Please provide an evaluation of the quality, clarity, originality and significance of this work, including a list of its pros and cons.',
        'required': True
    },
    'rating': {
        'order': 3,
        'value-dropdown': [
            '7: Top 10% of accepted papers, strong accept',
            '6: Top 25% of accepted papers, clear accept',
            '5: Top 50% of accepted papers, clear accept',
            '4: Marginally above acceptance threshold',
            '3: Marginally below acceptance threshold',
            '2: Clear rejection',
            '1: Strong rejection'
        ],
        'required': True
    },
    'confidence': {
        'order': 4,
        'value-radio': [
            '3: The reviewer is absolutely certain that the evaluation is correct and very familiar with the relevant literature',
            '2: The reviewer is fairly confident that the evaluation is correct',
            '1: The reviewer\'s evaluation is an educated guess'
        ],
        'required': True
    }
}

