#!/usr/bin/python

import sys, os

"""
GROUPS

Defines constants for CONF (the name of the conference), and for the names of each group.
All other groups will be named by joining the name with CONF: <CONF>/<NAME>

Example:

    CONF = 'my.conference/2017'
    PROGRAM_CHAIRS = 'Program_Chairs'

    --> my.conference/2017/Program_Chairs

"""

CONF = "informatik.uni-rostock.de/Informatik_Rostock/Ubiquitous_Computing/2017"
ADMIN = CONF + '/Admin'
PROGRAM_CHAIRS = CONF + '/Program_Chairs'
AREA_CHAIRS = CONF + '/Area_Chairs'
REVIEWERS = CONF + '/Reviewers'
## June 15th at 11:59 pm (CEST) = - 6hrs to EDT = 5:59 pm
DUE_TIMESTAMP = 1497563999000
WEBPATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '../webfield/conf.html'))
##2017, June 25th at 11:59 pm (CEST) = 17:59 EST
REVIEW_DUE = 1498427999000
## 2017, July 15th at 11:59 pm (CEST)
CAMERA_DUE = 1500155999000
##  2017, August 04
CONF_DATE = 1501891200000
"""
INVITATIONS

Defines constants for various invitations.
The full name of an invitation will be generated by joining the name with CONF by "/-/": <CONF>/-/<INVITATION_NAME>

Example:

    CONF = 'my.conference/2017'
    SUBMISSION = 'Submission'

    --> my.conference/2017/-/Submission

"""

SUBMISSION = CONF + '/-/Submission'
COMMENT = CONF + '/-/Comment'
COMMENTERS = CONF + '/Commenters'

""" Class members that can read/write submissions and comments """
CLASS_MEMBERS = CONF + '/Class_Members'
class_members =  ['max.schroeder@uni-rostock.de',
                  'stefan.luedtke2@uni-rostock.de',
                'sebastian.bader@uni-rostock.de',
                'thomas.kirste@uni-rostock.de',
                'albert.hein@uni-rostock.de',
                'martin.nyolt@uni-rostock.de',
                'kristina.yordanova2@uni-rostock.de',
                'frank.krueger2@uni-rostock.de',
                'tom.schmidt4@uni-rostock.de',
                'jasper.roloff@uni-rostock.de',
                'sebastian.rutofski@uni-rostock.de',
                'max.kaseler@uni-rostock.de',
                'erik.manthey@uni-rostock.de',
                'nic.scharlau@uni-rostock.de',
                'paul.lidzba@uni-rostock.de',
                'eric.kirbach@uni-rostock.de',
                'maximilian.lamster@uni-rostock.de',
                'paul.lahne2@uni-rostock.de',
                'tom.raddei@uni-rostock.de',
                'sergej.schimanski@uni-rostock.de',
                'maximilian.popko@uni-rostock.de',
                'karl.ginnuth@uni-rostock.de',
                'tim.bayer@uni-rostock.de',
                'jakob.zimmer@uni-rostock.de',
                  'mandler@cs.umass.edu']

"""
PARAMETERS

Dictionaries that represent argument combinations defining Group and Invitation permissions.

Example:

    restricted = {
        'readers': [CONF],
        'writers': [CONF],
        'signatories': [CONF],
    }

    The "restricted" configuration above will only allow the CONF group to read, write, and sign
    for the newly created Group that uses it.
"""

conf_params = {
    'readers': ['everyone'],
    'writers': [CONF],
    'signatories': [CONF],
    'web': WEBPATH
}

group_params = {
    'readers': [CONF],
    'writers': [CONF],
    'signatories': [CONF],
}

submission_params = {
    'readers': [CONF, CLASS_MEMBERS,PROGRAM_CHAIRS],
    'writers': [CONF],
    'invitees': [CLASS_MEMBERS, PROGRAM_CHAIRS],
    'signatures': [CONF],
    'process': os.path.abspath(os.path.join(os.path.dirname(__file__), '../process/submissionProcess.js'))
}

revision_params = {
    'readers': [CONF, CLASS_MEMBERS, PROGRAM_CHAIRS],
    'writers': [CONF],
    'signatures': [CONF]
}

comment_params = {
    'readers': [CONF, COMMENTERS],
    'writers': [CONF],
    'invitees': [COMMENTERS],
    'signatures': [CONF],
    'duedate': CONF_DATE
}

review_content = {
    'title': {
        'order': 1,
        'value-regex': '.{0,500}',
        'description': 'Brief summary of your review.',
        'required': True
    },
    'review': {
        'order': 2,
        'value-regex': '[\\S\\s]{1,5000}',
        'description': 'Please provide an evaluation of the quality, clarity, originality and significance of this work, including a list of its pros and cons.',
        'required': True
    },
    'rating': {
        'order': 3,
        'value-dropdown': [
            '5: Top 15% of accepted papers, strong accept',
            '4: Top 50% of accepted papers, clear accept',
            '3: Marginally above acceptance threshold',
            '2: Marginally below acceptance threshold',
            '1: Strong rejection'
        ],
        'required': True
    },
    'confidence': {
        'order': 4,
        'value-radio': [
            '3: The reviewer is absolutely certain that the evaluation is correct and very familiar with the relevant literature',
            '2: The reviewer is fairly confident that the evaluation is correct',
            '1: The reviewer\'s evaluation is an educated guess'
        ],
        'required': True
    }
}

submission_content = {
    'title': {
        'description': 'Title of paper.',
        'order': 1,
        'value-regex': '.{1,250}',
        'required':True
    },
    'authors': {
        'description': 'Comma separated list of author names.',
        'order': 2,
        'values-regex': "[^;,\\n]+(,[^,\\n]+)*",
        'required':True
    },
    'authorids': {
        'description': 'Comma separated list of author email addresses, lowercased, in the same order as above. For authors with existing OpenReview accounts, please make sure that the provided email address(es) match those listed in the author\'s profile.',
        'order': 3,
        'values-regex': "([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,},){0,}([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,})",
        'required':True
    },
    'keywords': {
        'description': 'Comma separated list of keywords.',
        'order': 6,
        'values-regex': "(^$)|[^;,\\n]+(,[^,\\n]+)*"
    },
    'TL;DR': {
        'description': '\"Too Long; Didn\'t Read\": a short sentence describing your paper',
        'order': 7,
        'value-regex': '[^\\n]{0,250}',
        'required':False
    },
    'abstract': {
        'description': 'Abstract of paper.',
        'order': 8,
        'value-regex': '[\\S\\s]{1,5000}',
        'required':True
    },
    'pdf': {
        'description': 'Upload a PDF file that ends with .pdf',
        'order': 9,
        'value-regex': 'upload',
        'required':True
    }
}

submission_reply = {
    'forum': None,
    'replyto': None,
    'invitation': None,
    'readers': {
        'description': 'The users who will be allowed to read the above content.',
        'values': [CLASS_MEMBERS]
    },
    'signatures': {
        'description': 'How your identity will be displayed with the above content.',
        'values-regex': '~.*'
    },
    'writers': {
        'values-regex': '~.*'
    },
    'content': submission_content
}

