#!/usr/bin/python

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../../../../../utils"))
import utils

"""
GROUPS

Defines constants for CONF (the name of the conference), and for the names of each group.
All other groups will be named by joining the name with CONF: <CONF>/<NAME>

Example:

    CONF = 'my.conference/2017'
    PROGRAM_CHAIRS = 'Program_Chairs'

    --> my.conference/2017/Program_Chairs

"""

CONF = "informatik.uni-rostock.de/Informatik_Rostock/Ubiquitous_Computing/2017"
ADMIN = CONF + '/Admin'
PROGRAM_CHAIRS = CONF + '/Program_Chairs'
AREA_CHAIRS = CONF + '/Area_Chairs'
REVIEWERS = CONF + '/Reviewers'
DUE_TIMESTAMP = 1497563999000
WEBPATH = utils.get_path('../webfield/conf.html', __file__)


"""
INVITATIONS

Defines constants for various invitations.
The full name of an invitation will be generated by joining the name with CONF by "/-/": <CONF>/-/<INVITATION_NAME>

Example:

    CONF = 'my.conference/2017'
    SUBMISSION = 'Submission'

    --> my.conference/2017/-/Submission

"""

SUBMISSION = CONF + '/-/Submission'
COMMENT = CONF + '/-/Comment'

""" Class members that can read/write submissions and comments """
CLASS_MEMBERS = CONF + '/Class_Members'
class_members =  ['max.schroeder@uni-rostock.de',
                  'stefan.luedtke2@uni-rostock.de',
                'sebastian.bader@uni-rostock.de',
                'thomas.kirste@uni-rostock.de',
                'albert.hein@uni-rostock.de',
                'martin.nyolt@uni-rostock.de',
                'kristina.yordanova2@uni-rostock.de',
                'frank.krueger2@uni-rostock.de',
                'tom.schmidt4@uni-rostock.de',
                'jasper.roloff@uni-rostock.de',
                'sebastian.rutofski@uni-rostock.de',
                'max.kaseler@uni-rostock.de',
                'erik.manthey@uni-rostock.de',
                'nic.scharlau@uni-rostock.de',
                'paul.lidzba@uni-rostock.de',
                'eric.kirbach@uni-rostock.de',
                'maximilian.lamster@uni-rostock.de',
                'paul.lahne2@uni-rostock.de',
                'tom.raddei@uni-rostock.de',
                'sergej.schimanski@uni-rostock.de',
                'maximilian.popko@uni-rostock.de',
                'karl.ginnuth@uni-rostock.de',
                'tim.bayer@uni-rostock.de',
                'jakob.zimmer@uni-rostock.de',
                  'mandler@cs.umass.edu']

"""
PARAMETERS

Dictionaries that represent argument combinations defining Group and Invitation permissions.

Example:

    restricted = {
        'readers': [CONF],
        'writers': [CONF],
        'signatories': [CONF],
    }

    The "restricted" configuration above will only allow the CONF group to read, write, and sign
    for the newly created Group that uses it.
"""

conf_params = {
    'readers': ['everyone'],
    'writers': [CONF],
    'signatories': [CONF],
    'web': WEBPATH
}

group_params = {
    'readers': [CONF],
    'writers': [CONF],
    'signatories': [CONF],
}

submission_params = {
    'readers': [CLASS_MEMBERS,PROGRAM_CHAIRS],
    'writers': [CONF],
    'invitees': [CLASS_MEMBERS, PROGRAM_CHAIRS],
    'signatures': [CONF],
    'process': utils.get_path('../process/submissionProcess.js', __file__)
}

comment_params = {
    'readers': [CLASS_MEMBERS, PROGRAM_CHAIRS],
    'writers': [CONF],
    'invitees': [CLASS_MEMBERS, PROGRAM_CHAIRS],
    'signatures': [CONF],
    'process': utils.get_path('../process/commentProcess.js', __file__)
}


