#!/usr/bin/python

import sys, os
from openreview import tools
"""
GROUPS

Defines constants for CONFERENCE_ID (the name of the conference), and for the names of each group.
All other groups will be named by joining the name with CONFERENCE_ID: <CONFERENCE_ID>/<NAME>

Example:

    CONFERENCE_ID = 'my.conference/2017'
    PROGRAM_CHAIRS = 'Program_Chairs'

    --> my.conference/2017/Program_Chairs

"""

CONFERENCE_ID = 'ICML.cc/2018/ECA'
PROGRAM_CHAIRS = CONFERENCE_ID + '/Program_Chairs'
AREA_CHAIRS = CONFERENCE_ID + '/Area_Chairs'
REVIEWERS = CONFERENCE_ID + '/Reviewers'

# GMT is 7 hours ahead of PST
SUBMISSION_TIMESTAMP = tools.timestamp_GMT(2018, month=6, day= 16, hour=3, minute=59)
REVIEW_TIMESTAMP = tools.timestamp_GMT(2018, month=6, day= 19, hour=3, minute=59)
WEBPATH = os.path.join(os.path.dirname(__file__), '../webfield/conferenceWebfield.js')


"""
INVITATIONS

Defines constants for various invitations.
The full name of an invitation will be generated by joining the name with CONFERENCE_ID by "/-/": <CONFERENCE_ID>/-/<INVITATION_NAME>

Example:

    CONFERENCE_ID = 'my.conference/2017'
    SUBMISSION = 'Submission'

    --> my.conference/2017/-/Submission

"""

SUBMISSION = CONFERENCE_ID + '/-/Submission'
COMMENT = CONFERENCE_ID + '/-/Comment'

JS_CONSTANTS = {
    'CONFERENCE': CONFERENCE_ID,
    'AREA_CHAIRS': AREA_CHAIRS,
    'PROGRAM_CHAIRS': PROGRAM_CHAIRS,
    'REVIEWERS': REVIEWERS,
    'TITLE': 'Efficient Credit Assignment in Deep Learning and Reinforcement Learning Workshop',
    'SUBTITLE': 'ICML 2018 ECA',
    'DEADLINE_STRING': 'June 15, 2018, 11:59 pm EST',
    'CONF_DATE_STRING': 'July 14-15, 2018',
    'INSTRUCTIONS': 'https://sites.google.com/view/icml-reproducibility-workshop/home',
    'WEBSITE': 'https://sites.google.com/view/creditassignmentindlanddrl/home',
    'LOCATION': 'Stockhome, Sweden',
    'SUBMISSION_INVITATION': SUBMISSION,
}

HOMEPAGE_TEMPLATE = "../webfield/conferenceWebfield.template"
"""
PARAMETERS

Dictionaries that represent argument combinations defining Group and Invitation permissions.

Example:

    restricted = {
        'readers': [CONFERENCE_ID],
        'writers': [CONFERENCE_ID],
        'signatories': [CONFERENCE_ID],
    }

    The "restricted" configuration above will only allow the CONFERENCE_ID group to read, write, and sign
    for the newly created Group that uses it.
"""
conference_params = {
    'id': CONFERENCE_ID,
    'readers': ['everyone'],
    'writers': [CONFERENCE_ID],
    'signatures': [],
    'signatories': [CONFERENCE_ID],
    'members': []
}

group_params = {
    'readers': [CONFERENCE_ID],
    'writers': [CONFERENCE_ID],
    'signatories': [CONFERENCE_ID],
    'signatures': [CONFERENCE_ID]
}

program_chairs_params = {
    'readers': [CONFERENCE_ID, PROGRAM_CHAIRS],
    'writers': [CONFERENCE_ID],
    'signatories': [CONFERENCE_ID, PROGRAM_CHAIRS],
    'signatures': [CONFERENCE_ID],
}

submission_params = {
    'readers': ['everyone'],
    'writers': [CONFERENCE_ID],
    'invitees': ['~'],
    'signatures': [CONFERENCE_ID],
    'process': os.path.join(os.path.dirname(__file__), '../process/submissionProcess.js')
}

comment_params = {
    'readers': ['everyone'],
    'writers': [CONFERENCE_ID],
    'invitees': ['~'],
    'signatures': [CONFERENCE_ID],
    'process': os.path.join(os.path.dirname(__file__), '../process/commentProcess.js')
}

review_params = {
    'readers': ['everyone'],
    'writers': [CONFERENCE_ID],
    'signatures': [CONFERENCE_ID],
    'process': os.path.join(os.path.dirname(__file__), '../process/officialReviewProcess.js'),
    'duedate': REVIEW_TIMESTAMP
}


"""
TEMPLATES

"""

submission_content_overwrite = {
    'authors': {
        'description': 'Comma separated list of author names.',
        'order': 2,
        'values-regex': "[^;,\\n]+(,[^,\\n]+)*",
        'required':True
    },
    'authorids': {
        'description': 'Comma separated list of author email addresses, lowercase, in the same order as above. For authors with existing OpenReview accounts, please make sure that the provided email address(es) match those listed in the author\'s profile.',
        'order': 3,
        'values-regex': "([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,},){0,}([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,})",
        'required':True
    },
}

review_content = {
    'title': {
        'order': 1,
        'value-regex': '.{0,500}',
        'description': 'Brief summary of your review (up to 500 chars).',
        'required': True
    },
    'review': {
        'order': 2,
        'value-regex': '[\\S\\s]{1,5000}',
        'description': 'Please provide an evaluation of the quality, clarity, originality and significance of this work, including a list of its pros and cons (up to 5000 chars).',
        'required': True
    },
    'rating': {
        'order': 4,
        'value-dropdown': [
            '5: Top 15% of accepted papers, strong accept',
            '4: Top 50% of accepted papers, clear accept',
            '3: Marginally above acceptance threshold',
            '2: Marginally below acceptance threshold',
            '1: Strong rejection'
        ],
        'required': True
    },
    'confidence': {
        'order': 5,
        'value-radio': [
            '3: The reviewer is absolutely certain that the evaluation is correct and very familiar with the relevant literature',
            '2: The reviewer is fairly confident that the evaluation is correct',
            '1: The reviewer\'s evaluation is an educated guess'
        ],
        'required': True
    }
}
