#!/usr/bin/env node

var fs = require('fs');
var request = require('request');

// The open review local url
var grpUrl = 'http://localhost:8529/_db/_system/openreview/groups';
var loginUrl = 'http://localhost:8529/_db/_system/openreview/login';

var headers = { 'User-Agent': 'test-create-script' };

//or3 request bodies
var userpass = {
  'id': 'akobren@host.com',
  'password': '12345678'
};

function or3post(url, body, headers) {
  this.url = url;
  this.method = 'POST';
  this.port = 80;
  this.json = true;
  this.body = body;
  this.headers = headers;
}

function callback(error, response, body) {
  if (!error && response.statusCode == 200) {
    return JSON.parse(body.body);
  } else {
  console.log("BODY");
  console.log(body);
  console.log("ERROR: " + error);
  console.log("RESPONSE: " + response.statusCode);
  }
}

var createReq = new or3post(grpUrl, userpass, headers);
var r = request(createReq, callback);
console.log(r)