#!/usr/bin/env node

var fs = require('fs');
var request = require('request');

// Here is where the hardcoded json data goes
// You could also load from a separate file, which might be cleaner:
// var testData = fs.ReadFileSync('file.json', 'utf8'); 
var testData = { data: [
  { a: 1, b: 2, c: 3 },
  { a: 4, b: 5, c: 6 },
  { a: 7, b: 8, c: 9 },
]};

var options = {
  url: 'http://echo.jpillora.com',  // Public echo server, change to localhost
  method: 'POST',                   // Could be PUT if you want to get fancy
  port: 80,                         // Probably need to change this too
  json: true,
  body: testData,
  headers: {
    'User-Agent': 'test-script'
  }
};
 
function callback(error, response, body) {
  if (!error && response.statusCode == 200) {
    var responseBody = JSON.parse(body.body);
	  console.log(responseBody); // Request returned successfully
  }
}
 
request(options, callback);
