# Creating SAC groups from Track Name for NAACL 2022
sac_name_dictionary = {
    'Phonology, Morphology and Word Segmentation': 'Phonology_Morphology_Word_Segmentation',
    'Information Extraction': 'Information_Extraction',
    'Computational Social Science and Cultural Analytics': 'CSSCA',
    'Information Retrieval and Text Mining': 'Info_Retrieval_Text_Mining',
    'Interpretability and Analysis of Models for NLP': 'IAM_for_NLP',
    'NLP Applications': 'NLP_Applications',
    'Question Answering': 'Question_Answering',
    'Discourse and Pragmatics': 'Discourse_and_Pragmatics',
    'Summarization': 'Summarization',
    'Language Generation': 'Language_Generation',
    'Sentiment Analysis and Stylistic Analysis': 'SASA',
    'Machine Learning for NLP: Classification and Structured Prediction Models': 'NLP_CSPM',
    'Machine Learning for NLP: Language Modeling and Sequence to Sequence Models': 'NLP_LMSSM',
    'Syntax: Tagging, Chunking, and Parsing': 'Syntax_TCP',
    'Language Resources and Evaluation': 'Language_Resources_Evaluation',
    'Linguistic Theories, Cognitive Modeling and Psycholinguistics': 'LCMP',
    'Dialogue and Interactive systems': 'Dialogue_Interactive_Systems',
    'Multilinguality': 'Multilinguality',
    'Ethics, Bias, and Fairness': 'Ethics_Bias_Fairness',
    'Semantics: Sentence-level Semantics and Textual Inference': 'Semantics_STI',
    'Semantics: Lexical Semantics': 'Semantics_LS',
    'Machine Translation': 'Machine_Translation',
    'Efficient methods in NLP': "Efficient_NLP",
    'Speech': 'Speech',
    'Language Grounding to Vision, Robotics and Beyond': 'LGVRB',
    'Special theme': 'Special_Theme'
    }