#!/usr/bin/env node

var fs = require('fs');
var request = require('request');

// The open review local url
var grpUrl = 'http://localhost:8529/_db/_system/openreview/groups';
var loginUrl = 'http://localhost:8529/_db/_system/openreview/login';
var noteUrl = 'http://localhost:8529/_db/_system/openreview/note';
var inviteUrl = 'http://localhost:8529/_db/_system/openreview/invitations';

var headers = { 'User-Agent': 'test-create-script' };

//or3 request bodies
var userpass = {
  'id': 'ari@host.com',
  'password': '12345678'
};

function or3post(url, body, headers) {
  this.url = url;
  this.method = 'POST';
  this.port = 8529;
  this.json = true;
  this.body = body;
  this.headers = headers;
}

function callback(error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log("SUCCESS")
    console.log(body)
  } else {
  console.log("ERROR: " + error);
  console.log("RESPONSE: " + response.statusCode);
  }
}

function loggedInHdr(token) {
  return {
  'Authorization': 'Bearer ' + token,
  'User-Agent': 'test-create-script',
  };
}

// INVITATION TO COMMENT
var comInv = {
  'id': 'arisconf/-/comments',
  'authors': ['ari@host.com'],
  'writers': ['arisconf/pc'],
  'readers': ['*'],
  'invitees':['*'],
  'reply': {
    'parent': null,     // should this be set to whatever is being commented on?
    'authors': ['~.*'],
    'writers': ['~.*'],
    'readers': ['*'],
    'content': {
      'title': '.{1,100}',
      'comment': '.{1,5000}'
    }
  },
  'process': function(noteID) {
  	     return true;  	       //send email to paper’s authors’ and reviewers’ email addresses
	     }
}

function create_comment_invite(url, o) {
    var loginReq = new or3post(loginUrl, userpass, headers);
    request(loginReq, function(error, response, body) {
      if (!error && response.statusCode == 200) {
        var token = body.token;
	var commentInvite = new or3post(url, o, loggedInHdr(token));
	console.log(commentInvite);
	request(commentInvite, callback);
    }
  });
}

create_comment_invite(inviteUrl, comInv);