#!/usr/bin/python

import sys, os
from openreview import tools
"""
GROUPS

Defines constants for CONFERENCE_ID (the name of the conference), and for the names of each group.
All other groups will be named by joining the name with CONFERENCE_ID: <CONFERENCE_ID>/<NAME>

Example:

    CONFERENCE_ID = 'my.conference/2017'
    PROGRAM_CHAIRS = 'Program_Chairs'

    --> my.conference/2017/Program_Chairs

"""

CONFERENCE_ID = 'MIDL.amsterdam/2019/Abstract'
PROGRAM_CHAIRS = CONFERENCE_ID + '/Program_Chairs'
AREA_CHAIRS = CONFERENCE_ID + '/Area_Chairs'
REVIEWERS = CONFERENCE_ID + '/Reviewers'
#
SUBMISSION_TIMESTAMP = tools.timestamp_GMT(2019, month=4, day= 15, hour=23, minute=59)
# REVIEW_TIMESTAMP = tools.timestamp_GMT(2018, month=9, day= 30, hour=23, minute=59)
WEBPATH = os.path.join(os.path.dirname(__file__), '../webfield/abstractWebfield.js')


"""
INVITATIONS

Defines constants for various invitations.
The full name of an invitation will be generated by joining the name with CONFERENCE_ID by "/-/": <CONFERENCE_ID>/-/<INVITATION_NAME>

Example:

    CONFERENCE_ID = 'my.conference/2017'
    SUBMISSION = 'Submission'

    --> my.conference/2017/-/Submission
"""

SUBMISSION = CONFERENCE_ID + '/-/Submission'
COMMENT = CONFERENCE_ID + '/-/Comment'


"""
PARAMETERS

Dictionaries that represent argument combinations defining Group and Invitation permissions.

Example:

    restricted = {
        'readers': [CONFERENCE_ID],
        'writers': [CONFERENCE_ID],
        'signatories': [CONFERENCE_ID],
    }

    The "restricted" configuration above will only allow the CONFERENCE_ID group to read, write, and sign
    for the newly created Group that uses it.
"""
conference_params = {
    'id': CONFERENCE_ID,
    'readers': ['everyone'],
    'writers': [CONFERENCE_ID],
    'signatures': [],
    'signatories': [CONFERENCE_ID],
    'members': []
}

group_params = {
    'readers': [CONFERENCE_ID],
    'writers': [CONFERENCE_ID],
    'signatories': [CONFERENCE_ID],
    'signatures': [CONFERENCE_ID]
}

program_chairs_params = {
    'readers': [CONFERENCE_ID, PROGRAM_CHAIRS],
    'writers': [CONFERENCE_ID],
    'signatories': [CONFERENCE_ID, PROGRAM_CHAIRS],
    'signatures': [CONFERENCE_ID],
}

submission_params = {
    'readers': ['everyone'],
    'writers': [CONFERENCE_ID],
    'invitees': ['~'],
    'signatures': [CONFERENCE_ID],
    'process': os.path.join(os.path.dirname(__file__), '../process/submissionProcess.js')
}

comment_params = {
    'readers': ['everyone'],
    'writers': [CONFERENCE_ID],
    'invitees': ['~'],
    'signatures': [CONFERENCE_ID],
    'process': os.path.join(os.path.dirname(__file__), '../process/commentProcess.js')
}

submission_content = {
    'title': {
        'description': 'Title of paper (up to 250 chars).',
        'order': 1,
        'value-regex': '.{1,250}',
        'required': True
    },
    'authors': {
        'description': 'Comma separated list of author names.',
        'order': 2,
        'values-regex': "[^;,\\n]+(,[^,\\n]+)*",
        'required': True
    },
    'authorids': {
        'description': 'Comma separated list of author email addresses, lowercase, in the same order as above. For authors with existing OpenReview accounts, please make sure that the provided email address(es) match those listed in the author\'s profile.',
        'order': 3,
        'values-regex': "([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,},){0,}([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,})",
        'required': True
    },
    'abstract': {
        'description': 'Abstract of paper (up to 5000 chars).',
        'order': 4,
        'value-regex': '[\\S\\s]{1,5000}',
        'required': True
    },
    'keywords': {
        'description': 'Comma separated list of keywords.',
        'order': 6,
        'values-regex': "(^$)|[^;,\\n]+(,[^,\\n]+)*"
    },
    'pdf': {
        'description': 'Upload a PDF file that ends with .pdf. Submissions can be up to three pages.',
        'order': 9,
        'value-regex': 'upload',
        'required': True
    },
    'author affiliation': {
        'description': 'Institution name(s) of the author(s)',
        'order': 10,
        'values-regex': "[^;,\\n]+(,[^,\\n]+)*",
        'required': False
    }
}